FROM node:18.18-alpine as build

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build --prod


FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist/perfect-ride-map /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
